export { Home } from './Home'
export { Details } from './Details'
export { Register } from './Register'
export { Notifications } from './Notifications'
export { PhysicalExercises } from './PhysicalExercises'
export { MapScreen } from './MapScreen'
export { ActivityHistory } from './activityHistory'
